### ISSUE TITLE
it knows that it's true but didn't exclamation point

### ISSUE THREAD

**Issue by swatwood** [EdwinWu1423/diligent-computing#5]
java UserOfMazeSolver  mazes/intersection_treasureNorth.txt 1 0 43
-----
| 0 |
|e**|
| * |
-----

true
-----
|E0 |
| **|
| * |
-----

**Comment by tinawong15** [comment]
I believe this issue is coming up because you are seeing an old version of our work. When cloning a repository, it is automatically on the branch `master`. In order to access the branch `v0`, you need to do `git checkout v0`. I tried this again on my computer, and the displayer worked. Please reopen the issue if this test still doesn't work for you after doing the above. Thank you for your time!
